apiVersion: v1
entries:
  oathkeeper:
  - apiVersion: v2
    appVersion: v0.39.0
    created: "2022-08-04T15:11:24.552654+02:00"
    dependencies:
    - alias: oathkeeper-maester
      condition: maester.enabled
      name: oathkeeper-maester
      repository: file://../oathkeeper-maester
      version: 0.24.5
    description: A Helm chart for deploying ORY Oathkeeper in Kubernetes
    digest: fed77b2ed49bd4ad6a99d6087e12291ba9eb1ccd2318a46c012b219d256287fc
    home: https://www.ory.sh/
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-oathkeeper.svg
    keywords:
    - zero-trust
    - beyond-corp
    - access-control
    - reverse-proxy
    - nginx
    - envoy
    - ambassador
    - auth-filter
    maintainers:
    - email: office@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: oathkeeper
    sources:
    - https://github.com/ory/oathkeeper
    - https://github.com/ory/k8s
    type: application
    urls:
    - oathkeeper-0.24.6.tgz
    version: 0.24.6
  - apiVersion: v2
    appVersion: v0.39.0
    created: "2022-08-04T15:11:24.546862+02:00"
    dependencies:
    - alias: oathkeeper-maester
      condition: maester.enabled
      name: oathkeeper-maester
      repository: file://../oathkeeper-maester
      version: 0.24.5
    description: A Helm chart for deploying ORY Oathkeeper in Kubernetes
    digest: 786d163737a63f9dc8061c7619734e1d7fd00a5823bae08e27529844c9d1f589
    home: https://www.ory.sh/
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-oathkeeper.svg
    keywords:
    - zero-trust
    - beyond-corp
    - access-control
    - reverse-proxy
    - nginx
    - envoy
    - ambassador
    - auth-filter
    maintainers:
    - email: office@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: oathkeeper
    sources:
    - https://github.com/ory/oathkeeper
    - https://github.com/ory/k8s
    type: application
    urls:
    - oathkeeper-0.24.5.tgz
    version: 0.24.5
generated: "2022-08-04T15:11:24.543916+02:00"
